// <auto-generated />
using Banomart.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banomart.Services.ProductAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banomart.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Accessories",
                            Description = "A durable, vintage-inspired canvas backpack with ample storage for daily essentials.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/02/08/15/33/journey-3983404_1280.jpg",
                            Name = "Vintage Canvas Backpack",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Home & Kitchen",
                            Description = "Eco-friendly, stainless steel water bottle with a leak-proof cap. Keeps drinks hot or cold for hours.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/23/09/52/water-2001912_1280.jpg",
                            Name = "Stainless Steel Water Bottle",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Electronics",
                            Description = "Comfortable wireless mouse with customizable buttons and adjustable DPI for precision control.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/04/07/13/13/wireless-mouse-2210970_1280.jpg",
                            Name = "Ergonomic Wireless Mouse",
                            Price = 29.949999999999999
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Groceries",
                            Description = "A pack of premium, organic green tea leaves rich in antioxidants and natural flavors.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2021/03/08/06/23/green-tea-6078275_1280.jpg",
                            Name = "Organic Green Tea Leaves",
                            Price = 15.5
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Fitness",
                            Description = "Non-slip yoga mat with a comfortable thickness and a carrying strap for easy transport.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/15/18/29/yoga-mat-1743203_1280.jpg",
                            Name = "Yoga Mat with Carrying Strap",
                            Price = 35.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
